# Generated by Django 3.1.4 on 2020-12-08 18:54

import designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designs',
            name='image_floor_one',
            field=models.ImageField(blank=True, upload_to='images_floors'),
        ),
        migrations.AddField(
            model_name='designs',
            name='image_floor_two',
            field=models.ImageField(blank=True, upload_to='images_floors'),
        ),
        migrations.AlterField(
            model_name='designs',
            name='baths',
            field=models.IntegerField(validators=[designs.models.is_negative]),
        ),
        migrations.AlterField(
            model_name='designs',
            name='beds',
            field=models.IntegerField(validators=[designs.models.is_negative]),
        ),
        migrations.AlterField(
            model_name='designs',
            name='garages',
            field=models.IntegerField(validators=[designs.models.is_negative]),
        ),
        migrations.AlterField(
            model_name='designs',
            name='price',
            field=models.FloatField(validators=[designs.models.is_negative]),
        ),
        migrations.AlterField(
            model_name='designs',
            name='stories',
            field=models.IntegerField(validators=[designs.models.is_negative]),
        ),
        migrations.AlterField(
            model_name='designs',
            name='total_area',
            field=models.IntegerField(validators=[designs.models.is_negative]),
        ),
    ]
