# Generated by Django 3.1.4 on 2020-12-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
